<a href="https://colab.research.google.com/github/arooshasolomon/DS-4002/blob/main/Python5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
Question 2
```



In [5]:
import numpy as np
from sympy import Matrix

# Define the coefficient matrices for H and K
A_H = np.array([[2, 4, 6], [1, 4, 5]]).T  # Corrected to column vectors
A_K = np.array([[5, -1, 1], [0, -14, -6]]).T  # Corrected to column vectors

# Construct the augmented matrix and find the null space
A = Matrix.hstack(Matrix(A_H), -Matrix(A_K))
null_space_vector = A.nullspace()[0]  # Get a basis vector for the null space

# Scale the solution to match the desired output
w = null_space_vector * (40 / null_space_vector[0])
w = w[:3]  # Extract only w

# Convert to integer representation
w = np.array(w).astype(int)

print("Nonzero vector w that generates the intersection line:")
print(w)

Nonzero vector w that generates the intersection line:
[ 40 -49   6]


In [ ]:
Question 4

In [6]:
import numpy as np
from sympy import Matrix

# matrix
A = Matrix([
    [1, 0, -7, 3],
    [0, 1, -5, 4],
    [7, -10, 1, -19]
])


null_space = A.nullspace()

basis_vectors = [np.array(vec).astype(float) for vec in null_space]

print("Basis for the null space of the given matrix:")
for vec in basis_vectors:
    print(vec)

Basis for the null space of the given matrix:
[[7.]
 [5.]
 [1.]
 [0.]]
[[-3.]
 [-4.]
 [ 0.]
 [ 1.]]


In [ ]:
Question 8

In [6]:
import numpy as np

# Define the vectors as columns of a matrix
v1 = np.array([1, 0, 0, 1])
v2 = np.array([-6, 0, 0, 6])
v3 = np.array([3, -2, 1, -1])

# Combine the vectors into a matrix
matrix = np.column_stack((v1, v2, v3))

# Compute the rank and perform QR decomposition
_, R = np.linalg.qr(matrix, mode='reduced')

# Identify the independent columns (pivot positions)
independent_columns = np.where(np.abs(R.diagonal()) > 1e-10)[0]

# Extract the independent vectors (basis)
basis_vectors = matrix[:, independent_columns]

# Print the result
print("The independent vectors (basis) are:")
print(basis_vectors)


The independent vectors (basis) are:
[[ 1 -6  3]
 [ 0  0 -2]
 [ 0  0  1]
 [ 1  6 -1]]


Question 11

In [13]:
import numpy as np

# Define the basis vectors as columns of matrix B
B = np.array([
    [1, 4, 5],
    [-4, 5, -7],
    [2, -3, 0]
])

# Define the coordinate vector [x]_B
X_andb = np.array([4, 0, -1])

# Compute x = B * [x]_B
x = B @ X_andb

# Print the result
print("The vector x is:")
print(x)


The vector x is:
[-1 -9  8]


Question 14

In [11]:
import numpy as np

# Define the basis vectors as columns of matrix B
B = np.array([
    [1, 2, 1],
    [0, 1, -1],
    [4, 9, 2]
])

# Define the vector x
x = np.array([6, -2, 19])

# Solve for [x]_B using linear algebra
x_B = np.linalg.solve(B, x)

# Print the result
print("The coordinate vector [x]_B is:")
print(x_B)


The coordinate vector [x]_B is:
[1. 1. 3.]
